compressionLevel: mixed

enableGlobalCache: false

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.17.1.cjs
