compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

pnpEnableEsmLoader: true

packageExtensions:
  react-node-resolver@*:
    peerDependencies:
      react: '*'
      react-dom: '*'

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.17.1.cjs
