import type { ManagedWorkflowBackend } from './managed/backend.js';

/** Common data-serving surface. Lifecycle, PostgreSQL-only coordination and
 * import operations stay outside this contract. SQLite remains single-host. */
export type WorkflowDataBackend = Pick<
  ManagedWorkflowBackend,
  | 'getTree'
  | 'listProjectPathsForHostedIo'
  | 'loadHostedProject'
  | 'saveHostedProject'
  | 'readHostedText'
  | 'hostedPathExists'
  | 'resolveManagedRelativeProjectText'
  | 'createWorkflowFolderItem'
  | 'renameWorkflowFolderItem'
  | 'moveWorkflowFolder'
  | 'deleteWorkflowFolderItem'
  | 'createWorkflowProjectItem'
  | 'renameWorkflowProjectItem'
  | 'moveWorkflowProject'
  | 'duplicateWorkflowProjectItem'
  | 'uploadWorkflowProjectItem'
  | 'readWorkflowProjectDownload'
  | 'readWorkflowProjectReferenceSnapshots'
  | 'listWorkflowProjectReferenceCatalog'
  | 'listWorkflowPublishedVersions'
  | 'readWorkflowPublishedVersionDownload'
  | 'readWorkflowPublishedVersionPreview'
  | 'setWorkflowPublishedVersionStar'
  | 'setWorkflowPublishedVersionComment'
  | 'restoreWorkflowPublishedVersion'
  | 'publishWorkflowProjectItem'
  | 'updateWorkflowEndpointAccess'
  | 'listWorkflowProjectWebApps'
  | 'publishWorkflowProjectWebApps'
  | 'updateWorkflowProjectWebAppAccess'
  | 'unpublishWorkflowProjectWebApp'
  | 'unpublishWorkflowProjectItem'
  | 'deleteWorkflowProjectItem'
  | 'loadPublishedExecutionProject'
  | 'loadLatestExecutionProject'
  | 'loadPublishedWebAppExecutionProject'
  | 'loadLatestWebAppExecutionProject'
  | 'resolveWebAppAccessPolicy'
  | 'createProjectReferenceLoader'
  | 'loadSubgraphTarget'
  | 'listWorkflowRecordingWorkflows'
  | 'listWorkflowRecordingRunsPage'
  | 'listWorkflowRunStatisticsCatalog'
  | 'getWorkflowRunStatistics'
  | 'readWorkflowRecordingArtifact'
  | 'deleteWorkflowRecording'
  | 'persistWorkflowExecutionRecording'
>;
