import type { BuiltInNodeType } from '@valerypopoff/rivet2-core';

export const NODE_REFERENCE_BASE_URL = 'https://valerypopoff.github.io/rivet2.0/node-reference';
export const INTERNAL_BUILT_IN_NODE_TYPES_WITHOUT_NODE_REFERENCE = new Set<BuiltInNodeType>(['nodePrefabInstance']);

export const BUILT_IN_NODE_DOCUMENTATION_SLUGS: Partial<Record<BuiltInNodeType, string>> = {
  abortGraph: 'abort-graph',
  appendToDataset: 'append-to-dataset',
  array: 'array',
  assembleMessage: 'assemble-message',
  assemblePrompt: 'assemble-prompt',
  audio: 'audio',
  boolean: 'bool',
  callGraph: 'call-graph',
  chat: 'chat',
  chatLoop: 'chat-loop',
  chunk: 'chunk',
  code: 'code',
  codeNew: 'code-new',
  coalesce: 'coalesce',
  comment: 'comment',
  compare: 'compare',
  context: 'context',
  createDataset: 'create-dataset',
  cron: 'cron',
  datasetNearestNeighbors: 'knn-dataset',
  delay: 'delay',
  delegateFunctionCall: 'delegate-tool-call',
  destructure: 'destructure',
  didRun: 'did-run',
  document: 'document',
  evaluate: 'evaluate',
  expression: 'expression',
  externalCall: 'external-call',
  extractJson: 'extract-json',
  extractMarkdownCodeBlocks: 'extract-markdown-code-blocks',
  extractObjectPath: 'extract-object-path',
  extractRegex: 'extract-with-regex',
  extractYaml: 'extract-yaml',
  filter: 'filter',
  getAllDatasets: 'get-all-datasets',
  getDatasetRow: 'get-dataset-row',
  getEmbedding: 'get-embedding',
  getGlobal: 'get-global',
  gptFunction: 'gpt-function',
  graphInput: 'graph-input',
  graphOutput: 'graph-output',
  graphReference: 'graph-reference',
  hash: 'hash',
  httpCall: 'http-call',
  if: 'if',
  ifElse: 'if-else',
  image: 'image',
  join: 'join',
  jsFilter: 'js-filter',
  jsMap: 'js-map',
  listGraphs: 'list-graphs',
  llmChatV2: 'llm-chat',
  loadDataset: 'load-dataset',
  loopController: 'loop-controller',
  loopUntil: 'loop-until',
  match: 'match',
  mcpDiscovery: 'mcp-discovery',
  mcpGetPrompt: 'mcp-get-prompt',
  mcpToolCall: 'mcp-tool-call',
  number: 'number',
  object: 'object',
  passthrough: 'passthrough',
  playAudio: 'play-audio',
  pop: 'pop',
  prompt: 'prompt',
  raceInputs: 'race-inputs',
  raiseEvent: 'raise-event',
  randomNumber: 'RNG',
  readAllFiles: 'read-all-files',
  readDirectory: 'read-directory',
  readFile: 'read-file',
  referencedGraphAlias: 'referenced-graph-alias',
  replaceDataset: 'replace-dataset',
  reportProgress: 'report-progress',
  setGlobal: 'set-global',
  shuffle: 'shuffle',
  slice: 'slice',
  split: 'split-text',
  subGraph: 'subgraph',
  text: 'text',
  toJson: 'to-json',
  toMarkdownTable: 'to-markdown-table',
  toTree: 'to-tree',
  toYaml: 'to-yaml',
  trimChatMessages: 'trim-chat-messages',
  urlReference: 'url-reference',
  userInput: 'user-input',
  vectorNearestNeighbors: 'vector-knn',
  vectorStore: 'vector-store',
  waitForEvent: 'wait-for-event',
};

export function getBuiltInNodeDocumentationUrl(nodeType: string): string | undefined {
  if (!Object.prototype.hasOwnProperty.call(BUILT_IN_NODE_DOCUMENTATION_SLUGS, nodeType)) {
    return undefined;
  }

  const slug = (BUILT_IN_NODE_DOCUMENTATION_SLUGS as Record<string, string | undefined>)[nodeType];
  if (!slug) {
    return undefined;
  }

  return `${NODE_REFERENCE_BASE_URL}/${slug}`;
}
