// test-style: fixture-read: extracts only ZIPs generated by test-owned exports.
import fs from 'node:fs/promises';
import path from 'node:path';
import { inflateRawSync } from 'node:zlib';
import {
  GraphOutputNodeImpl,
  TextNodeImpl,
  SubGraphNodeImpl,
  getGraphBoundary,
  serializeProject,
  type Project,
  type GraphId,
  type ProjectId,
  type PortId,
} from '@valerypopoff/rivet2-node';
import type { BundleSnapshot, BundleSource } from '../../routes/workflows/project-bundle.js';

export function projectBundleFixture(): { root: BundleSnapshot; child: BundleSnapshot; source: BundleSource } {
  const childGraph = 'child-main' as GraphId,
    rootGraph = 'main' as GraphId;
  const text = TextNodeImpl.create();
  text.data.text = 'child-result';
  const output = GraphOutputNodeImpl.create();
  output.data.id = 'result';
  const child: Project = {
    metadata: { id: 'bundle-child' as ProjectId, title: '子供', description: '', mainGraphId: childGraph },
    graphs: {
      [childGraph]: {
        metadata: { id: childGraph, name: 'Child', description: '' },
        nodes: [text, output],
        connections: [
          { outputNodeId: text.id, outputId: 'output' as PortId, inputNodeId: output.id, inputId: 'value' as PortId },
        ],
      },
    },
  };
  const subgraph = SubGraphNodeImpl.create();
  subgraph.data.graphId = childGraph;
  subgraph.data.targetProjectId = child.metadata.id;
  subgraph.data.targetVersion = 'latest';
  subgraph.data.targetBoundary = getGraphBoundary(child, childGraph)!;
  const rootOutput = GraphOutputNodeImpl.create();
  rootOutput.data.id = 'result';
  const project: Project = {
    metadata: { id: 'bundle-root' as ProjectId, title: 'Root', description: '', mainGraphId: rootGraph },
    graphs: {
      [rootGraph]: {
        metadata: { id: rootGraph, name: 'Main', description: '' },
        nodes: [subgraph, rootOutput],
        connections: [
          {
            outputNodeId: subgraph.id,
            outputId: 'result' as PortId,
            inputNodeId: rootOutput.id,
            inputId: 'value' as PortId,
          },
        ],
      },
    },
  };
  const root: BundleSnapshot = {
    project,
    projectContents: serializeProject(project) as string,
    selectedVersion: 'latest',
  };
  const childSnapshot: BundleSnapshot = {
    project: child,
    projectContents: serializeProject(child) as string,
    selectedVersion: 'latest',
  };
  const source: BundleSource = {
    root: async () => root,
    target: async () => childSnapshot,
    reference: async () => childSnapshot,
  };
  return { root, child: childSnapshot, source };
}

/** Tiny test-only extractor for the small ordinary ZIP fixtures (not a public archive parser). */
export async function extractProjectBundleFixture(bytes: Buffer, directory: string) {
  const end = bytes.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  if (end < 0) throw new Error('Missing ZIP directory.');
  let offset = bytes.readUInt32LE(end + 16);
  for (let index = 0; index < bytes.readUInt16LE(end + 10); index++) {
    if (bytes.readUInt32LE(offset) !== 0x02014b50) throw new Error('Invalid ZIP directory entry.');
    const method = bytes.readUInt16LE(offset + 10),
      size = bytes.readUInt32LE(offset + 20);
    const nameLength = bytes.readUInt16LE(offset + 28),
      extraLength = bytes.readUInt16LE(offset + 30),
      commentLength = bytes.readUInt16LE(offset + 32);
    const local = bytes.readUInt32LE(offset + 42),
      name = bytes.subarray(offset + 46, offset + 46 + nameLength).toString('utf8');
    if (name.startsWith('/') || name.includes('\\') || name.includes(':') || name.split('/').includes('..'))
      throw new Error('Unsafe test ZIP path.');
    const start = local + 30 + bytes.readUInt16LE(local + 26) + bytes.readUInt16LE(local + 28);
    const compressed = bytes.subarray(start, start + size);
    if (method !== 0 && method !== 8) throw new Error('Unsupported test ZIP compression.');
    const target = path.join(directory, name);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, method === 8 ? inflateRawSync(compressed) : compressed);
    offset += 46 + nameLength + extraLength + commentLength;
  }
}
