apiVersion: v1
kind: Service
metadata:
  name: {{ include "rivet.backendHeadlessServiceName" . }}
  labels:
    {{- include "rivet.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  clusterIP: None
  selector:
    {{- include "rivet.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.api.port }}
      targetPort: api-http
    - name: executor
      port: {{ .Values.service.executor.port }}
      targetPort: executor-http
