apiVersion: v1
kind: Service
metadata:
  name: {{ include "rivet.proxyServiceName" . }}
  labels:
    {{- include "rivet.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  selector:
    {{- include "rivet.componentLabels" (dict "root" . "component" "proxy") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.proxy.port }}
      targetPort: http
